<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') 
		 ->appendStylesheet('/jqGrid/css/ui.jqgrid.css')
                 ->appendStylesheet('/css/jquery-ui-1.10.1.custom.css')
                 ->appendStylesheet('/plugins/ui.multiselect.css') 
?>
        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/js/bootstrap.min.js')
			              ->prependFile($this->basePath() . '/js/clock.js')
	//		              ->prependFile($this->basePath() . '/js/jquery.min.js') 
	->prependFile('http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js', 'text/javascript')
	->prependFile('http://ajax.googleapis.com/ajax/libs/jquery/1.8/jquery.min.js', 'text/javascript')
	->appendFile('/jqGrid/js/i18n/grid.locale-pl.js', 'text/javascript')
	->appendFile('/plugins/ui.multiselect.js', 'text/javascript')
	->appendFile('/jqGrid/js/jquery.jqGrid.min.js', 'text/javascript')
?>
    </head>
    <body onload="setInterval('updateClock()', 200);">
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Skeleton Application') ?></a>
                    <div class="nav-collapse collapse">
 	                <ul class="nav"> 
                            <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                            <li class="active"><a href="<?php echo $this->url('album') ?>"><?php echo $this->translate('Album') ?></a></li>
                            <li class="active"><a href="<?php echo $this->url('disc') ?>"><?php echo $this->translate('Disc') ?></a></li>
                            <li class="active"><a href="<?php echo $this->url('disc', array('action' => 'grid')) ?>"><?php echo $this->translate('Disc_grid') ?></a></li>


                        </ul>
                    </div><!--/.nav-collapse -->
			<div style="top: 0px; right:10px; position: absolute; width: 250px;">
			<div style="text-align: right; width:160px; float:left;">
			<?php IF($this->zfcUserIdentity()) { echo $this->zfcUserIdentity()->getEmail(); ?>
			<br /><a href="<?php echo $this->url('zfcuser/logout') ?>"><?php echo $this->translate('Wyloguj'); } ?></a>
			</div>
			<div style="text-align: left; width:80px; float:right;">
			<span id="clock"></span><br>
			<?php echo date("Y-m-d"); ?>
			</div>
			</div>
                </div>
            </div>
        </div>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2005 - 2012 by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
