<?php
// module/Disc/view/disc/disc/index.phtml:

$title = 'My discs';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('disc', array('action'=>'add'));?>">Add new disc</a>
</p>

<table class="table">
<tr>
    <th>Title</th>
    <th>Artist</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($discs as $disc) : ?>
<tr>
    <td><?php echo $this->escapeHtml($disc->title);?></td>
    <td><?php echo $this->escapeHtml($disc->artist);?></td>
    <td>
        <a href="<?php echo $this->url('disc',
            array('action'=>'edit', 'id' => $disc->id));?>">Edit</a>
        <a href="<?php echo $this->url('disc',
            array('action'=>'delete', 'id' => $disc->id));?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>
